### PR TITLE
Add Travis support with validate and linting

### PR DESCRIPTION
**Pull request by Callek**
Theres lots of linting options, all of the --no-* ones we currently fail, I didn't invest in time to fix any "WARNING:" ones, all the currently failing ones that the linter marks as an ERROR I fixed.

### CODE REVIEW

**Comment by djmitche** [comment]
I like this fix, but remember that puppet is in hg - this is just a mirror.  Can you file a bug with the patch attached?  And is there some way to have hg filter out the whitespace changes (a la `git diff --ignore-space-changes`) so we can look at the non-whitespace changes only?

**Comment by djmitche** [comment]
Here's the diff without whitespace changes:
```
diff --git a/.gemfile b/.gemfile
new file mode 100644
index 0000000..2b2854d
--- /dev/null
+++ b/.gemfile
@@ -0,0 +1,4 @@
+source 'https://rubygems.org'
+
+gem 'puppet', '3.7.0', :require => false
+gem 'puppet-lint'
diff --git a/.travis.yml b/.travis.yml
new file mode 100644
index 0000000..b6a808d
--- /dev/null
+++ b/.travis.yml
@@ -0,0 +1,36 @@
+language: ruby
+rvm:
+  - 1.8.7
+
+script:
+  #- "ln -s manifests/moco-config.pp manifests/config.pp"
+  #- "ln -s manifests/moco-nodes.pp manifests/nodes.pp"
+  - "puppet parser validate `find modules -name '*.pp'`"
+  - "puppet-lint --no-arrow_alignment-check --no-80chars-check \
+      --no-documentation-check --no-double_quoted_strings-check \
+      --no-variable_scope-check --no-case_without_default-check \
+      --no-variables_not_enclosed-check --no-only_variable_string-check \
+      --no-ensure_first_param-check --no-unquoted_file_mode-check \
+      --no-variable_contains_dash-check --no-parameter_order-check \
+      --no-file_mode-check --no-nested_classes_or_defines \
+      --no-quoted_booleans --no-puppet_url_without_modules \
+      --no-selector_inside_resource --no-unquoted_resource_title \
+      --no-names_containing_dash \
+      --log-format '%{path} - %{KIND}: %{message} on line %{line} - %{check}'
+      modules"
+
+gemfile: .gemfile
+
+# The channel name "irc.mozilla.org#releng" is encrypted against mozilla/build-buildbot-configs to prevent IRC spam of forks
+# Generated with: travis encrypt --repo mozilla/build-puppet  --skip-version-check irc.mozilla.org#releng
+notifications:
+  irc:
+    channels:
+      - secure: "DlqdA6eYvBRFOLIUnOs38nzy61g20+bu1OyiANIcm0U7e9lRNZNMnmTqG2F8YmzgJgnWfQeogkpF2tsFVAVMuXeRIfC9xSbsCE4oWucScp5SJiOvp68284/jpEhCZWAscer3J+9F5Md+voW4foteAY70GPms1xNJkfy1gs2UZKs="
+    on_success: always
+    on_failure: always
+    template:
+      - "\x02%{repository}\x0314#%{build_number}\x03\x02 (%{branch} - %{commit} : %{author}): \x02\x0312%{message}\x02\x03"
+      - "\x02Change view\x02 : \x0314%{compare_url}\x03"
+      - "\x02Build details\x02 : \x0314%{build_url}\x03"
+      - "\x02Commit message\x02 : \x0314%{commit_message}\x03"
diff --git a/modules/assert/tests/assert.pp b/modules/assert/tests/assert.pp
index af9c24f..78c62f9 100644
--- a/modules/assert/tests/assert.pp
+++ b/modules/assert/tests/assert.pp
@@ -1,8 +1,9 @@
+# lint:ignore:autoloader_layout
 class { 'one': }
 
 # two should be applied
 assert { 'This should succeed':
   condition => true
 } ->
 class { 'two': }
 
@@ -31,8 +32,9 @@ class two {
 
 class three {
   notify { 'this is from the third class': }
 }
 
 class four {
   notify { 'this is from the fourth class': }
 }
+# lint:endignore
\ No newline at end of file
diff --git a/modules/buildmaster/manifests/queue.pp b/modules/buildmaster/manifests/queue.pp
index 3e51c18..ce217c4 100644
--- a/modules/buildmaster/manifests/queue.pp
+++ b/modules/buildmaster/manifests/queue.pp
@@ -68,23 +68,22 @@ class buildmaster::queue {
                 "MozillaPulse==1.2.1",
                 "amqp==1.4.6",
                 "anyjson==0.3.3",
                 "kombu==3.0.23",
                 "pytz==2015.6",
             ];
     }
 
-    define nrpe_custom {
     nrpe::custom {
-            "$name":
-                content => template("buildmaster/${name}.erb"),
+        "pulse_publisher.cfg":
+            content => template("buildmaster/pulse_publisher.cfg.erb");
+        "command_runner.cfg":
+            content => template("buildmaster/command_runner.cfg.erb");
     }
-    }
-    nrpe_custom {["pulse_publisher.cfg", "command_runner.cfg"]: }
 
     mercurial::repo {
         "clone-tools":
             hg_repo => "${config::buildbot_tools_hg_repo}",
             dst_dir => "${buildmaster::settings::queue_dir}/tools",
             user    => "${users::builder::username}",
             branch  => "default";
     }
diff --git a/modules/collectd/manifests/plugins/unixsock.pp b/modules/collectd/manifests/plugins/unixsock.pp
index d368ea2..3b3a8a5 100644
--- a/modules/collectd/manifests/plugins/unixsock.pp
+++ b/modules/collectd/manifests/plugins/unixsock.pp
@@ -12,18 +12,21 @@ class collectd::plugins::unixsock {
     case $::operatingsystem {
         'CentOS', 'Ubuntu': {
             $socketgroup = 'collectd'
             $args = [ 'SocketFile "/var/run/collectd-unixsock"',
                       "SocketGroup ${socketgroup}",
                       'SocketPerms 0770',
                       'DeleteSocket true', ]
         }
-        default: {fail("Collectd plugin ${title} is not supported with ${::operatingsystem}")}
+        default: {
+            fail("Collectd plugin ${title} is not supported with ${::operatingsystem}")
         }
+    }
+
     # members of this group may interact with collectd via the unixsocket
     # if group write permissions are set on the socket file
     group {
         $socketgroup:
             ensure => present,
             system => true;
     }
     collectd::util::config_gen {$plugin_name: arg_array => $args}
diff --git a/modules/dirs/manifests/usr/local.pp b/modules/dirs/manifests/usr/local.pp
index dcab90d..518ee2d 100644
--- a/modules/dirs/manifests/usr/local.pp
+++ b/modules/dirs/manifests/usr/local.pp
@@ -1,12 +1,10 @@
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 class dirs::usr::local {
-      
-     
     file {
         "/usr/local":
             ensure => directory,
             mode => 0755;
     }
 }
diff --git a/modules/disableservices/manifests/user.pp b/modules/disableservices/manifests/user.pp
index 574bead..458c7d2 100644
--- a/modules/disableservices/manifests/user.pp
+++ b/modules/disableservices/manifests/user.pp
@@ -2,17 +2,17 @@
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
 class disableservices::user($username, $group, $home) {
     # disable services that require a user account
     case $::operatingsystem {
         Darwin : {
             osxutils::defaults {
-                '${username}-disablescreensaver':
+                "${username}-disablescreensaver":
                     domain => "${home}/Library/Preferences/ByHost/com.apple.screensaver.$sp_platform_uuid",
                     key => "idleTime",
                     value => "0";
             }
             file {
                 "${home}/Library/Preferences/ByHost":
                     ensure => directory,
                     owner => $username,
diff --git a/modules/foopy/manifests/init.pp b/modules/foopy/manifests/init.pp
index 0171cb3..17aeb53 100644
--- a/modules/foopy/manifests/init.pp
+++ b/modules/foopy/manifests/init.pp
@@ -79,17 +79,17 @@ class foopy {
             ensure => link,
             target => "/etc/logrotate.d/watch_devices",
             require => File['/etc/logrotate.d/watch_devices'];
     }
     
     # Obsolete
     file {
         # Bug 875599: these files should no longer exist
-        ["/builds/start_cp.sh",
+        [ "/builds/start_cp.sh",
           "/builds/stop_cp.sh",
           "/builds/check.sh",
           "/builds/tegra_status.txt",
           "/builds/check.log",
           "/builds/check2.log",
           "/builds/tegra_stats.log"]:
               ensure => absent;
     }
diff --git a/modules/gui/manifests/init.pp b/modules/gui/manifests/init.pp
index d45eae5..812db83 100644
--- a/modules/gui/manifests/init.pp
+++ b/modules/gui/manifests/init.pp
@@ -127,17 +127,17 @@ class gui(
                 "${users::builder::home}/.xsessionrc":
                     content => "DESKTOP_SESSION=ubuntu\n",
                     owner => $::users::builder::username,
                     group => $::users::builder::group,
                     mode => 0644,
                     notify => Service['x11'];
 
                 # make sure the builder user doesn't have any funny business
-                ["${users::builder::home}/.xsession",
+                [ "${users::builder::home}/.xsession",
                   "${users::builder::home}/.xinitrc",
                   "${users::builder::home}/.Xsession"]:
                     ensure => absent;
             }
 
             service {
                 'Xsession':
                     # we do not ensure this is running; the system will start
diff --git a/modules/mig/manifests/agent/checkin.pp b/modules/mig/manifests/agent/checkin.pp
index 8b3389b..df8a4eb 100644
--- a/modules/mig/manifests/agent/checkin.pp
+++ b/modules/mig/manifests/agent/checkin.pp
@@ -9,14 +9,14 @@ class mig::agent::checkin {
         installservice => "off",
         discoverpublicip => "on",
         checkin => "on",
         moduletimeout => "300s",
         apiurl => "https://api.mig.mozilla.org/api/v1/"
     }
     # ensure some of the service files aren't present
     file {
-        ["/etc/cron.d/mig-agent", "/etc/init/mig-agent.conf",
+        [ "/etc/cron.d/mig-agent", "/etc/init/mig-agent.conf",
           "/etc/init.d/mig-agent", "/etc/systemd/system/mig-agent.service"]:
             ensure => absent
     }
     include runner::tasks::mig_agent
 }
diff --git a/modules/packages/manifests/7z920.pp b/modules/packages/manifests/7z920.pp
index 768ecc5..d0495f5 100644
--- a/modules/packages/manifests/7z920.pp
+++ b/modules/packages/manifests/7z920.pp
@@ -3,9 +3,9 @@
 #file, You can obtain one at http://mozilla.org/MPL/2.0/.
 class packages::7z920 {
     # Source comes from http://www.7-zip.org/
     # This is required to install Mozilla build package
     packages::pkgmsi {"7-Zip 9.20":
         msi             => "7z920.msi",
         install_options => ['/quiet'];
     }
- }
+}
diff --git a/modules/packages/manifests/fonts.pp b/modules/packages/manifests/fonts.pp
index bfc7b20..46ae62f 100644
--- a/modules/packages/manifests/fonts.pp
+++ b/modules/packages/manifests/fonts.pp
@@ -1,16 +1,16 @@
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 class packages::fonts {
     case $::operatingsystem {
         Ubuntu: {
             package {
-                ["fonts-kacst-one", "fonts-kacst", "fonts-liberation",
+                [ "fonts-kacst-one", "fonts-kacst", "fonts-liberation",
                   "ttf-indic-fonts-core", "ttf-kannada-fonts", "ttf-dejavu",
                   "ttf-oriya-fonts", "ttf-punjabi-fonts", "ttf-arphic-uming",
                   "ttf-paktype", "fonts-stix", "fonts-unfonts-core",
                   "fonts-unfonts-extra", "fonts-vlgothic", "ttf-sazanami-mincho"]:
                     ensure => latest;
             }
         }
         Darwin: {
diff --git a/modules/packages/manifests/gstreamer.pp b/modules/packages/manifests/gstreamer.pp
index 9c695ad..7b6c7d2 100644
--- a/modules/packages/manifests/gstreamer.pp
+++ b/modules/packages/manifests/gstreamer.pp
@@ -1,16 +1,16 @@
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 class packages::gstreamer {
     case $::operatingsystem {
         Ubuntu: {
             package {
-                ["gstreamer0.10-ffmpeg", "gstreamer0.10-plugins-base",
+                [ "gstreamer0.10-ffmpeg", "gstreamer0.10-plugins-base",
                   "gstreamer0.10-plugins-good", "gstreamer0.10-plugins-ugly",
                   # plugins-bad contains a libfaad-based AAC decoder that will make
                   # tests succeed - see bug 912854
                   "gstreamer0.10-plugins-bad"]:
                     ensure => latest;
             }
         }
         default: {
diff --git a/modules/packages/manifests/mesa.pp b/modules/packages/manifests/mesa.pp
index 6a9c846..91ef07b 100644
--- a/modules/packages/manifests/mesa.pp
+++ b/modules/packages/manifests/mesa.pp
@@ -4,27 +4,27 @@
 class packages::mesa {
     case $::operatingsystem {
         Ubuntu: {
             case $::hardwaremodel {
                 "i686": {
                     package {
                         # This package is a recompiled version of
                         # https://launchpad.net/ubuntu/+source/mesa
-                        ["libgl1-mesa-dri", "libgl1-mesa-glx", "libglapi-mesa",
+                        [ "libgl1-mesa-dri", "libgl1-mesa-glx", "libglapi-mesa",
                           "libglu1-mesa", "libxatracker1"]:
                             ensure => '8.0.4-0ubuntu0.6mozilla1';
                     }
                 }
                 "x86_64": {
                     package {
                         # This package is a recompiled version of
                         # https://launchpad.net/ubuntu/+source/mesa
                         # libgl1-mesa-dev:i386 is required by B2G emulators, Bug 1013634
-                        ["libgl1-mesa-dri", "libgl1-mesa-glx", "libglapi-mesa",
+                        [ "libgl1-mesa-dri", "libgl1-mesa-glx", "libglapi-mesa",
                           "libglu1-mesa", "libxatracker1", "libgl1-mesa-dev:i386"]:
                             ensure => '8.0.4-0ubuntu0.6mozilla1';
                     }
                 }
             }
         }
         default: {
             fail("cannot install on $::operatingsystem")
diff --git a/modules/packages/manifests/mozilla/mig_agent.pp b/modules/packages/manifests/mozilla/mig_agent.pp
index 681a956..6eb9052 100644
--- a/modules/packages/manifests/mozilla/mig_agent.pp
+++ b/modules/packages/manifests/mozilla/mig_agent.pp
@@ -35,9 +35,9 @@ class packages::mozilla::mig_agent {
                     version => '20150910+37e52e1.prod-x86_64',
                     os_version_specific => false;
             } -> Anchor['packages::mozilla::mig_agent::end']
         }
         default: {
             fail("mig is not supported on ${::operatingsystem}")
         }
     }
- }
+}
diff --git a/modules/registry/tests/registry_examples.pp b/modules/registry/tests/registry_examples.pp
index 3f44968..3328c69 100644
--- a/modules/registry/tests/registry_examples.pp
+++ b/modules/registry/tests/registry_examples.pp
@@ -8,16 +8,17 @@
 #
 # = Requires
 #
 # = Sample Usage
 #
 #     include registry_example
 #
 # (MARKUP: http://links.puppetlabs.com/puppet_manifest_documentation)
+# lint:ignore:autoloader_layout
 class registry_example {
   registry_key { 'HKLM\Software\Vendor':
     ensure => present,
   }
 
   # This should trigger a duplicate resource with HKLM
   # registry_key { 'HKEY_LOCAL_MACHINE\Software\Vendor':
   #   ensure => present,
@@ -80,8 +81,9 @@ class registry_example {
   registry_value { 'HKLM\Software\Vendor\Bar\valuearray3':
     ensure => present,
     type   => array,
     data   => $some_array,
   }
 }
 
 include registry_example
+# lint:endignore
diff --git a/modules/releaserunner/manifests/init.pp b/modules/releaserunner/manifests/init.pp
index 7daf2d6..556cdff 100644
--- a/modules/releaserunner/manifests/init.pp
+++ b/modules/releaserunner/manifests/init.pp
@@ -73,17 +73,17 @@ class releaserunner {
             owner     => "${users::builder::username}",
             group     => "${users::builder::group}",
             content   => secret('releaserunner_ssh_key'),
             show_diff => false;
         "${releaserunner::settings::root}/docker-worker-pub.pem":
             require   => Python::Virtualenv["${releaserunner::settings::root}"],
             owner     => "${users::builder::username}",
             group     => "${users::builder::group}",
-            source    => "puppet:///modules/$module_name/docker-worker-pub.pem"
+            source    => "puppet:///modules/$module_name/docker-worker-pub.pem";
         # XXX: Todo name funsize_signing_pvt_key better for current use-case
         "${releaserunner::settings::root}/id_rsa":
             require     => Python::Virtualenv["${releaserunner::settings::root}"],
             mode        => 600,
             owner       => "${users::builder::username}",
             group       => "${users::builder::group}",
             content     => secret("funsize_signing_pvt_key"),
             show_diff   => false;
diff --git a/modules/releaserunner/manifests/services.pp b/modules/releaserunner/manifests/services.pp
index e31e850..4e4347a 100644
--- a/modules/releaserunner/manifests/services.pp
+++ b/modules/releaserunner/manifests/services.pp
@@ -5,14 +5,14 @@ class releaserunner::services {
     include ::config
     include packages::mozilla::supervisor
     include releaserunner::settings
 
     supervisord::supervise {
         "releaserunner":
             command      => "${releaserunner::settings::tools_dst}/buildfarm/release/release-runner.sh ${releaserunner::settings::root} ${releaserunner::settings::logfile} ${releaserunner::settings::root}/release-runner.ini",
             user         => $::config::builder_username,
-            require      => [File["${releaserunner::settings::root}/release-runner.ini"],
+            require      => [ File["${releaserunner::settings::root}/release-runner.ini"],
                               Python::Virtualenv["${releaserunner::settings::root}"],
                               Mercurial::Repo["releaserunner-tools"]],
             extra_config => template("${module_name}/extra_config.erb")
     }
 }
diff --git a/modules/rsyslog/manifests/init.pp b/modules/rsyslog/manifests/init.pp
index 85c3d37..d21b171 100644
--- a/modules/rsyslog/manifests/init.pp
+++ b/modules/rsyslog/manifests/init.pp
@@ -1,17 +1,18 @@
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 class rsyslog {
     include packages::rsyslog
 
     case $::operatingsystem {
         CentOS,Ubuntu: {
-            service { "rsyslog":
+            service {
+              "rsyslog":
                 require => Class["packages::rsyslog"],
                 ensure => running,
                 enable => true;
             }
             file {
                 "/etc/rsyslog.conf":
                     ensure => present,
                     source => "puppet:///modules/rsyslog/rsyslog.conf",
diff --git a/modules/selfserve_agent/manifests/services.pp b/modules/selfserve_agent/manifests/services.pp
index f77bc86..15c4b4f 100644
--- a/modules/selfserve_agent/manifests/services.pp
+++ b/modules/selfserve_agent/manifests/services.pp
@@ -16,17 +16,17 @@ class selfserve_agent::services {
             group   => $::config::builder_group,
             show_diff => false;
     }
 
     supervisord::supervise {
         "selfserve-agent":
             command      => "${selfserve_agent::settings::root}/bin/selfserve-agent --config-file ${selfserve_agent::settings::root}/selfserve-agent.ini --wait -v",
             user         => $::config::builder_username,
-            require      => [File["${selfserve_agent::settings::root}/selfserve-agent.ini"],
+            require      => [ File["${selfserve_agent::settings::root}/selfserve-agent.ini"],
                               Python::Virtualenv["${selfserve_agent::settings::root}"]],
             extra_config => template("${module_name}/extra_config.erb");
     }
 
     exec {
         "restart-selfserve-agent":
             command     => "/usr/bin/supervisorctl restart selfserve-agent",
             refreshonly => true,
diff --git a/modules/shipit_notifier/manifests/services.pp b/modules/shipit_notifier/manifests/services.pp
index 9739c6c..7da2007 100644
--- a/modules/shipit_notifier/manifests/services.pp
+++ b/modules/shipit_notifier/manifests/services.pp
@@ -5,14 +5,14 @@ class shipit_notifier::services {
     include ::config
     include packages::mozilla::supervisor
     include shipit_notifier::settings
 
     supervisord::supervise {
         "shipit_notifier":
             command      => "${shipit_notifier::settings::root}/bin/python ${shipit_notifier::settings::tools_dst}/buildfarm/release/shipit-notifier.py -c ${shipit_notifier::settings::root}/shipit_notifier.ini",
             user         => $::config::builder_username,
-            require      => [File["${shipit_notifier::settings::root}/shipit_notifier.ini"],
+            require      => [ File["${shipit_notifier::settings::root}/shipit_notifier.ini"],
                               Python::Virtualenv["${shipit_notifier::settings::root}"],
                               Mercurial::Repo["shipit_notifier_tools"]],
             extra_config => template("${module_name}/extra_config.erb")
     }
 }
diff --git a/modules/shipit_notifier/manifests/settings.pp b/modules/shipit_notifier/manifests/settings.pp
index 7590dbe..65c76d1 100644
--- a/modules/shipit_notifier/manifests/settings.pp
+++ b/modules/shipit_notifier/manifests/settings.pp
@@ -1,9 +1,9 @@
-	# This Source Code Form is subject to the terms of the Mozilla Public
+# This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
 class shipit_notifier::settings {
     include ::config
 
     $root = $config::shipit_notifier_root
     $tools_dst = "${root}/tools"
diff --git a/modules/signingserver/manifests/instance.pp b/modules/signingserver/manifests/instance.pp
index a85674f..a993af8 100644
--- a/modules/signingserver/manifests/instance.pp
+++ b/modules/signingserver/manifests/instance.pp
@@ -125,17 +125,17 @@ define signingserver::instance(
             "${basedir}/tools/release/signing/signing_wrapper.sh":
                 user => $user,
                 runas => 'root',
                 command => "${basedir}/tools/release/signing/signing_wrapper.sh";
         }
     }
 
     file {
-        [$signed_dir,
+        [ $signed_dir,
           $unsigned_dir,
           $secrets_dir,
           $signcode_keydir,
           $sha2signcode_keydir,
           $gpg_homedir,
           $mar_keydir,
           $dmg_keydir,
           $server_certdir]:
diff --git a/modules/signingworker/manifests/services.pp b/modules/signingworker/manifests/services.pp
index 0159ca9..5bc11bf 100644
--- a/modules/signingworker/manifests/services.pp
+++ b/modules/signingworker/manifests/services.pp
@@ -2,17 +2,17 @@ class signingworker::services {
     include ::config
     include signingworker::settings
     include packages::mozilla::supervisor
 
     supervisord::supervise {
         "signingworker":
             command      => "${signingworker::settings::root}/bin/signing-worker --admin.conf ${signingworker::settings::root}/config.json",
             user         => $::config::builder_username,
-            require      => [File["${signingworker::settings::root}/config.json"],
+            require      => [ File["${signingworker::settings::root}/config.json"],
                               File["${signingworker::settings::root}/passwords.json"],
                               Mercurial::Repo["signingworker-tools"]],
             extra_config => template("${module_name}/supervisor_config.erb");
     }
     exec {
         "restart-signingworker":
             command     => "/usr/bin/supervisorctl restart signingworker",
             refreshonly => true,
diff --git a/modules/talos/manifests/init.pp b/modules/talos/manifests/init.pp
index fe31fee..7b9fb85 100644
--- a/modules/talos/manifests/init.pp
+++ b/modules/talos/manifests/init.pp
@@ -57,17 +57,17 @@ class talos {
                 }
             }
         }
     }
 
     case $::operatingsystem {
         Darwin, CentOS, Ubuntu: {
             file {
-                ["/builds/slave/talos-data",
+                [ "/builds/slave/talos-data",
                   $talos::settings::apachedocumentroot]:
                     ensure => directory,
                     owner => "$users::builder::username",
                     group => "$users::builder::group",
                     mode => 0755;
             }
             file {
                 "/builds/talos-slave":
diff --git a/modules/toplevel/manifests/server/buildmaster/seamonkey.pp b/modules/toplevel/manifests/server/buildmaster/seamonkey.pp
index 2f6b10a..5739d16 100644
--- a/modules/toplevel/manifests/server/buildmaster/seamonkey.pp
+++ b/modules/toplevel/manifests/server/buildmaster/seamonkey.pp
@@ -1,12 +1,12 @@
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
 # seamonkey buildbot master
 
-class toplevel::server::buildmaster::mozilla inherits toplevel::server::buildmaster {
+class toplevel::server::buildmaster::seamonkey inherits toplevel::server::buildmaster {
     include buildmaster::base
     include buildmaster::queue
     include buildmaster::settings
     include packages::procmail # for lockfile
 }
diff --git a/modules/tweaks/manifests/cron.pp b/modules/tweaks/manifests/cron.pp
index 098a322..4aad030 100644
--- a/modules/tweaks/manifests/cron.pp
+++ b/modules/tweaks/manifests/cron.pp
@@ -1,17 +1,17 @@
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
 class tweaks::cron {
     case $::operatingsystem {
         Ubuntu: {
             file {
-                ["/etc/cron.weekly/apt-xapian-index", "/etc/cron.weekly/man-db",
+                [ "/etc/cron.weekly/apt-xapian-index", "/etc/cron.weekly/man-db",
                   "/etc/cron.daily/apache2", "/etc/cron.daily/apport", "/etc/cron.daily/apt",
                   "/etc/cron.daily/aptitude", "/etc/cron.daily/bsdmainutils", "/etc/cron.daily/man-db",
                   "/etc/cron.daily/mlocate", "/etc/cron.daily/popularity-contest", "/etc/cron.daily/standard",
                   "/etc/cron.daily/update-notifier-common"]:
                     ensure => absent;
             }
         }
         default: {
diff --git a/modules/tweaks/manifests/windows_setkms.pp b/modules/tweaks/manifests/windows_setkms.pp
index 0e926fc..4dec45b 100644
--- a/modules/tweaks/manifests/windows_setkms.pp
+++ b/modules/tweaks/manifests/windows_setkms.pp
@@ -1,10 +1,10 @@
 # This Source Code Form is subject to the terms of the Mozilla Public
 # License, v. 2.0. If a copy of the MPL was not distributed with this
 # file, You can obtain one at http://mozilla.org/MPL/2.0/.
 
-class tweaks::windows_activation {
+class tweaks::windows_setkms {
     shared::execonce { "ActivateKMS":
         require => Class["tweaks::windows_setkms"],
         command => 'C:\Windows\System32\cscript.exe C:\windows\system32\slmgr.vbs /ato';
     }
 }
```

**Comment by djmitche** [comment]
The only bit I'm worried about there is the windows tweak (the last hunk), as I expect the tweak currently isn't working, and will suddenly start working.  @markcor what do you think?

Also, how can we go about running this on code before putting it up for review?

**Comment by Callek** [comment]
It's been run on my own forks travis:  https://travis-ci.org/Callek/build-puppet

**Comment by djmitche** [comment]
Yeah, but that doesn't help with patches written in hg

**Comment by Callek** [comment]
Also noteworthy, looking at https://dxr.mozilla.org/build-central/search?q=path%3Apuppet+tweaks%3A%3Awindows&redirect=false&case=true I don't see any personal worry about the windows tweaks stuff (lots of things not used afaict)

Also a future todo for me is to build a docker init or some such that can run these validate/lint checks locally, but in the meantime to run the checks outside github/travis I'd expect we need to either have ``puppet validate`` and ``puppet-lint`` locally, and manually run, or build your patch on a github fork.

**Comment by Callek** [comment]
p.s. for future posterity https://bugzil.la/1234961 is the bug that was filed for this PR

**Comment by markcor** [comment]
The class tweaks::windows_setkms  does not work, so it can be removed.

**Comment by Callek** [comment]
This is now in live code: https://github.com/mozilla/build-puppet/compare/634c799ec30b...7f016222c49b

**Pull request closed without merging**
